### ISSUE TITLE
Problem installing plugin

### ISSUE THREAD

**Issue by micha-silver** [ConservationInternational/trends.earth#318]
I'm trying to install in QGIS 10.13 on Debian Linux. First I tried directly thru the plugin manager. This is the error that appeared when trying to load the plugin:

```
Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 

ImportError: /home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/summary_numba.so: undefined symbol: PyInstance_Type 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 53, in classFactory
    return LDMPPlugin(iface)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 100, in __init__
    self.dlg_calculate = DlgCalculate()
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 437, in __init__
    self.dlg_calculate_ld = DlgCalculateLD()
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 474, in __init__
    from LDMP.calculate_ldn import DlgCalculateOneStep, DlgCalculateLDNSummaryTableAdmin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate_ldn.py", line 48, in 
    from LDMP.summary_numba import merge_xtabs_i16, xtab_i16
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: /home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/summary_numba.so: undefined symbol: PyInstance_Type

Python version: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0] 
QGIS version: 3.10.11-A Coruña A Coruña, exported 
```

Then I downloaded the zipfile from [https://s3.amazonaws.com/trends.earth/sharing/LDMP_QGIS3.zip](url) and got a different error:
```
Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 

KeyError: 'Can only index numba types with slices with no start or stop, got 4.' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 49, in classFactory
    from LDMP.plugin import LDMPPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 24, in 
    from LDMP.download_data import DlgDownload
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/download_data.py", line 30, in 
    from LDMP.calculate import DlgCalculateBase, get_script_slug
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 59, in 
    from LDMP.calculate_numba import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate_numba.py", line 130, in 
    @cc.export('ldn_total_deg', 'f4[4](i2[:,:], b1[:,:], f4[:,:])')
  File "/usr/lib/python3/dist-packages/numba/pycc/cc.py", line 136, in export
    fn_args, fn_retty = sigutils.normalize_signature(sig)
  File "/usr/lib/python3/dist-packages/numba/core/sigutils.py", line 24, in normalize_signature
    parsed = _parse_signature_string(sig)
  File "/usr/lib/python3/dist-packages/numba/core/sigutils.py", line 14, in _parse_signature_string
    return eval(signature_str, {}, types.__dict__)
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/numba/core/types/abstract.py", line 186, in __getitem__
    ndim, layout = self._determine_array_spec(args)
  File "/usr/lib/python3/dist-packages/numba/core/types/abstract.py", line 211, in _determine_array_spec
    raise KeyError(f"Can only index numba types with slices with no start or stop, got {args}.")
KeyError: 'Can only index numba types with slices with no start or stop, got 4.'


Python version: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0] 
QGIS version: 3.10.11-A Coruña A Coruña, exported 
```
Any ideas how to proceed?
Thanks

**Comment by micha-silver** [comment]
I should add that on my machine I have python 3.8.6 and numba 0.51

**Comment by MLNoon** [comment]
Hello and thank you for your message. Please update to QGIS v3.14 or higher ([https://qgis.org/en/site/forusers/download.html](https://qgis.org/en/site/forusers/download.html)) and install from the Plugins menu by selecting 'Manage and Install plugins...' search for Trends.Earth and select 'Install plugin'.

**Comment by micha-silver** [comment]
Hi:
Following your suggestion, I Updated to QGIS 3.16 from the repos. Still the same error. (I'm on Debian testing) :

```
KeyError: 'Can only index numba types with slices with no start or stop, got 4.' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 49, in classFactory
    from LDMP.plugin import LDMPPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 24, in 
    from LDMP.download_data import DlgDownload
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/download_data.py", line 30, in 
    from LDMP.calculate import DlgCalculateBase, get_script_slug
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 59, in 
    from LDMP.calculate_numba import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/micha/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate_numba.py", line 130, in 
    @cc.export('ldn_total_deg', 'f4[4](i2[:,:], b1[:,:], f4[:,:])')
  File "/usr/lib/python3/dist-packages/numba/pycc/cc.py", line 136, in export
    fn_args, fn_retty = sigutils.normalize_signature(sig)
  File "/usr/lib/python3/dist-packages/numba/core/sigutils.py", line 24, in normalize_signature
    parsed = _parse_signature_string(sig)
  File "/usr/lib/python3/dist-packages/numba/core/sigutils.py", line 14, in _parse_signature_string
    return eval(signature_str, {}, types.__dict__)
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/numba/core/types/abstract.py", line 186, in __getitem__
    ndim, layout = self._determine_array_spec(args)
  File "/usr/lib/python3/dist-packages/numba/core/types/abstract.py", line 211, in _determine_array_spec
    raise KeyError(f"Can only index numba types with slices with no start or stop, got {args}.")
KeyError: 'Can only index numba types with slices with no start or stop, got 4.'


Python version: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0] 
QGIS version: 3.16.0-Hannover Hannover, 43b64b13f3 

```
Thanks, Micha

**Comment by micha-silver** [comment]
One additional detail: Just to test, I setup a conda environment with python 3.7, then installed QGIS (independant of the system installation) with all dependencies. It gave me version 3.14. Then I tried to load the trends.earth plugin. Same prob appeared :-(

Regards, Micha

**Comment by azvoleff** [comment]
Hmm... not sure why you are seeing that error. Are you running on Linux or MacOS?

**Comment by micha-silver** [comment]
Debian testing


⁣Arava Drainage Authority
Cell: +972-523-665918

**Comment by micha-silver** [comment]
Getting back to this issue, today I tried to **remove** the python3-numba package, and now the plugin loads properly.
??

Regards, Micha

**Comment by ricardogsilva** [comment]
I'm having a similar problem as @micha-silver. However I don't have `python3-numba` installed on my system.

Installed the plugin via QGIS plugin installer, then got the same error:

```
ImportError: /home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/summary_numba.so: undefined symbol: PyInstance_Type
```

I'm on Ubuntu 20.04, using QGIS 3.14.

**Comment by BrachyS** [comment]
> Getting back to this issue, today I tried to **remove** the python3-numba package, and now the plugin loads properly.
> ??
> 
> Regards, Micha

Hi Micha,
I had the exact same issue. I tried to delete numba (0.50.1-py3.8) from the site-packages folder but it did not work for me. Maybe have to do with the numba version? How did you remove the numba package? I am wondering if you have new insights on this issue. Thanks! 
Best,
Sabrina

**Comment by YG1975** [comment]
Hello,
I am having the same issue "Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method". I work on a Mac (BigSur 11.2.3), and have QGIS versions 2.18, 3.16-LTR and 3.18.1. In both 3.X versions I have the same issue and in the 2.18 the plugin does not even appear in the list of plugins...

Some help so that it works in the 3.X versions wold be much appreciated.
Best regards.
Yaniss

**Comment by YG1975** [comment]
The latest (1.0.2); I uninstalled and re-installed the plugin but nothing changed.

**Comment by luipir** [comment]
@azvoleff FYI
changing in line: https://github.com/ConservationInternational/trends.earth/blob/develop/LDMP/calculate_numba.py#L130
`@cc.export('ldn_total_deg', 'f4[4](i2[:,:], b1[:,:], f4[:,:])')`
as
`@cc.export('ldn_total_deg', 'f4[:](i2[:,:], b1[:,:], f4[:,:])')`
fix the issue

**Comment by christiankaiser** [comment]
I did have the same issue on macOS 10.15.7 with QGIS 3.16.8 and Python 3.8.7 and the fix @luipir suggested did solve this issue.

**Comment by azvoleff** [comment]
Fixed in develop.

**Comment by kamaulindhardt** [comment]
I have just experienced the same error with my attempt to install trends.earth plugin on by windows. Any idea what is going on here?

`Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method `

```
AttributeError: module 'time' has no attribute 'clock' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/kamaulindhardt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\__init__.py", line 49, in classFactory
    from LDMP.plugin import LDMPPlugin
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/kamaulindhardt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\plugin.py", line 26, in 
    from LDMP.jobs import DlgJobs
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/kamaulindhardt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\jobs.py", line 39, in 
    from LDMP.plot import DlgPlotTimeries
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/kamaulindhardt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\plot.py", line 18, in 
    import pyqtgraph as pg
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\pyqtgraph\__init__.py", line 204, in 
    from .graphicsItems.VTickGroup import *
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in 
    from .. import functions as fn
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\pyqtgraph\functions.py", line 17, in 
    from . import debug
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\pyqtgraph\debug.py", line 11, in 
    from . import ptime
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs\pyqtgraph\ptime.py", line 24, in 
    cstart = systime.clock()  ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.0-Odense Odense, decaadbb31 

Python Path:
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
C:\Users\kamaulindhardt\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
C:/Users/kamaulindhardt/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/kamaulindhardt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.20.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.20.0\bin
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/kamaulindhardt/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/QGIS
```

**Comment by anantapradhan** [comment]
Python error: Couldn't load plugin 'sz_module' due to an error when calling its classFactory() method See message log (Python Error) for more details.

same error

**Comment by azvoleff** [comment]
@anantapradhan - what OS version, QGIS version, and plugin version are you using?

**Comment by Mountain-Horn** [comment]
I installed the latest version of QGIS 3.24 Tisler, I faced the problem mentioned;
Python error: Couldn't load plugin 'processing_fusion' due to an error when calling its classFactory() method See message log (Python Error) for more details.
Before installed QGIS I have installed Anaconda and Python 27.
It will be helpful for me if anyone give a suggestion to get rid of this error.

**Comment by HendrikHamacher** [comment]
> I installed the latest version of QGIS 3.24 Tisler, I faced the problem mentioned; Python error: Couldn't load plugin 'processing_fusion' due to an error when calling its classFactory() method See message log (Python Error) for more details. Before installed QGIS I have installed Anaconda and Python 27. It will be helpful for me if anyone give a suggestion to get rid of this error.

Same issue here!

**Comment by sebjwallace** [comment]
@luipir solution works.

Download the latest ZIP release here
https://github.com/ConservationInternational/trends.earth/releases

Unzip it and open this file in any text or code editor: calculate_numba.py
Go to line 130 and replace the '4' to ':' so it looks like this:
'f4[:](i2[:,:], b1[:,:], f4[:,:])'

Zip the LDMP folder up again and install it as a ZIP from the plugins manager.

**Comment by azvoleff** [comment]
Thanks @sebjwallace. This is fixed in the development version and we'll be making a new release from that code (on the develop branch right now) soon. That will also bring in a host of other bugfixes and new features. In the interim I'll leave this open as we may make one more final release of the old 1.0 branch of trends.earth.

**Comment by andersan** [comment]
This issue is happening for me with version 2.0 of the plugin. I am trying to install it via the plugin manager in QGIS (v.  3.26.0)

Running in Ubuntu 20.04.

I can try installing from ZIP later but wanted to make it clear that there is still an issue in 2.0.


> Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/gui/DlgTimeSeries.ui' 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 91, in classFactory
>     from LDMP.plugin import LDMPPlugin  # noqa: autoimport
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 43, in 
>     from .timeseries import show_time_series
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/timeseries.py", line 35, in 
>     Ui_DlgTimeseries, _ = uic.loadUiType(
>   File "/usr/lib/python3/dist-packages/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
>     return __PyQtLoadUiType(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 199, in loadUiType
>     winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports,
>   File "/usr/lib/python3/dist-packages/PyQt5/uic/Compiler/compiler.py", line 111, in compileUi
>     w = self.parse(input_stream, resource_suffix)
>   File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 1020, in parse
>     document = parse(filename)
>   File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
>     tree.parse(source, parser)
>   File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
>     source = open(source, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/gui/DlgTimeSeries.ui'
> 
> 
> Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] 
> QGIS version: 3.26.0-Buenos Aires Buenos Aires, 0aece2818e

**Comment by azvoleff** [comment]
@andersan  - looks like you are seeing a different problem. And looking back seems there are actually three different problems listed on this issue. The initial reports were related to numba, while @kamaulindhardt is seeing something from `pyqtgraph`, and you are seeing something related to a ui file for the GUI. I'm closing this one as the main issue is fixed, and I'll shift your report @andersan into a new issue. @kamaulindhardt if you still see an error with the latest version please open a new issue with any error messages you are seeing.

**Comment by carmenbelenm** [comment]
I'm trying to install in QGIS | 3.28.9-Firenze on MacOs. First I tried directly thru the plugin manager, then with the latest ZIP release. This is the error that appeared when trying to load the plugin:

No se pudo cargar el complemento 'LDMP' 

RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. If using conda try: #> conda install clang_osx-64 clangxx_osx-64 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 117, in 
    from . import conf  # noqa: autoimport
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/conf.py", line 14, in 
    from .reports.utils import default_report_disclaimer
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/reports/utils.py", line 8, in 
    from ..jobs import manager
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/jobs/manager.py", line 23, in 
    from te_algorithms.gdal.util import combine_all_bands_into_vrt
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/util.py", line 14, in 
    from .util_numba import _accumulate_dicts
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs/te_algorithms/gdal/util_numba.py", line 29, in 
    cc = CC("util_numba")
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/pycc/cc.py", line 65, in __init__
    self._toolchain = Toolchain()
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/pycc/platform.py", line 78, in __init__
    self._raise_external_compiler_error()
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/pycc/platform.py", line 121, in _raise_external_compiler_error
    raise RuntimeError(msg)
RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. If using conda try:

#> conda install clang_osx-64 clangxx_osx-64


Versión de Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versión de QGIS: 3.28.9-Firenze Firenze, 66f4d63ad4 

Ruta de Python:
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-14_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-14_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-2/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-10_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-2/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-10_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-3/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-4_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-3/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-4_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-2/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-10_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-2/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-10_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-3/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-4_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-3/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-4_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-2/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-10_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP-2/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-10_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-14_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-14_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-14_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-14_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-14_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/Users/carmenmartinez/trends_earth_binaries_2-1-14_3-28
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Users/carmenmartinez/Library/Application Support/QGIS/QGIS3/profiles/default/python
D:\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc
